if [ -x /usr/bin/update-desktop-database ]; then
  /usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
  if [ -x /usr/bin/gtk-update-icon-cache ]; then
    /usr/bin/gtk-update-icon-cache -f usr/share/icons/hicolor >/dev/null 2>&1
  fi
fi

( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/include ; rm -rf pngconf.h )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/include ; ln -sf libpng16/pngconf.h pngconf.h )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/include ; rm -rf pnglibconf.h )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/include ; ln -sf libpng16/pnglibconf.h pnglibconf.h )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/include ; rm -rf png.h )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/include ; ln -sf libpng16/png.h png.h )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libjpeg.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libjpeg.so.8 libjpeg.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libgif.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libgif.so.7.0.0 libgif.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libwebp.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libwebp.so.7.0.5 libwebp.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libpixman-1.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libpixman-1.so.0.38.4 libpixman-1.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libcairo.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libcairo.so.2.11702.0 libcairo.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libcairo.so.2 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libcairo.so.2.11702.0 libcairo.so.2 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libpangoft2-1.0.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libpangoft2-1.0.so.0.4200.4 libpangoft2-1.0.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libgio-2.0.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libgio-2.0.so.0.5600.4 libgio-2.0.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libpangocairo-1.0.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libpangocairo-1.0.so.0.4200.4 libpangocairo-1.0.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libexif.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libexif.so.12.3.3 libexif.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libexpat.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libexpat.so.1.6.9 libexpat.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libtiff.so.5 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libtiff.so.5.4.0 libtiff.so.5 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libgmodule-2.0.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libgmodule-2.0.so.0.5600.4 libgmodule-2.0.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libpangocairo-1.0.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libpangocairo-1.0.so.0.4200.4 libpangocairo-1.0.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libpango-1.0.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libpango-1.0.so.0.4200.4 libpango-1.0.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libfribidi.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libfribidi.so.0.4.0 libfribidi.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libz.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libz.so.1.2.11 libz.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf liblcms2.so.2 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf liblcms2.so.2.0.8 liblcms2.so.2 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libgsf-1.so.114 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libgsf-1.so.114.0.46 libgsf-1.so.114 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libpng16.so.16 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libpng16.so.16.37.0 libpng16.so.16 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libgif.so.7 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libgif.so.7.0.0 libgif.so.7 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libpng16.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libpng16.so.16.37.0 libpng16.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libwebp.so.7 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libwebp.so.7.0.5 libwebp.so.7 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libfreetype.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libfreetype.so.6.17.1 libfreetype.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libpango-1.0.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libpango-1.0.so.0.4200.4 libpango-1.0.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libfribidi.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libfribidi.so.0.4.0 libfribidi.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libgobject-2.0.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libgobject-2.0.so.0.5600.4 libgobject-2.0.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libharfbuzz.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libharfbuzz.so.0.20503.0 libharfbuzz.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libgsf-1.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libgsf-1.so.114.0.46 libgsf-1.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libgdk_pixbuf-2.0.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libgdk_pixbuf-2.0.so.0.3612.0 libgdk_pixbuf-2.0.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libwebpmux.so.3 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libwebpmux.so.3.0.4 libwebpmux.so.3 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libharfbuzz.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libharfbuzz.so.0.20503.0 libharfbuzz.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libvips.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libvips.so.42.11.0 libvips.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libexif.so.12 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libexif.so.12.3.3 libexif.so.12 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libtiff.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libtiff.so.5.4.0 libtiff.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libpng.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libpng16.so libpng.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libgthread-2.0.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libgthread-2.0.so.0.5600.4 libgthread-2.0.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libwebpdemux.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libwebpdemux.so.2.0.6 libwebpdemux.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libvips-cpp.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libvips-cpp.so.42.11.0 libvips-cpp.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libwebpmux.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libwebpmux.so.3.0.4 libwebpmux.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf librsvg-2.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf librsvg-2.so.2.46.0 librsvg-2.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libffi.so.6 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libffi.so.6.0.4 libffi.so.6 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf liborc-0.4.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf liborc-0.4.so.0.28.0 liborc-0.4.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libwebpdemux.so.2 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libwebpdemux.so.2.0.6 libwebpdemux.so.2 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libpixman-1.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libpixman-1.so.0.38.4 libpixman-1.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libvips-cpp.so.42 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libvips-cpp.so.42.11.0 libvips-cpp.so.42 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf librsvg-2.so.2 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf librsvg-2.so.2.46.0 librsvg-2.so.2 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libgdk_pixbuf-2.0.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libgdk_pixbuf-2.0.so.0.3612.0 libgdk_pixbuf-2.0.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libglib-2.0.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libglib-2.0.so.0.5600.4 libglib-2.0.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libglib-2.0.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libglib-2.0.so.0.5600.4 libglib-2.0.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libcairo-gobject.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libcairo-gobject.so.2.11702.0 libcairo-gobject.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libgobject-2.0.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libgobject-2.0.so.0.5600.4 libgobject-2.0.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libexpat.so.1 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libexpat.so.1.6.9 libexpat.so.1 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libvips.so.42 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libvips.so.42.11.0 libvips.so.42 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libpangoft2-1.0.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libpangoft2-1.0.so.0.4200.4 libpangoft2-1.0.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libfontconfig.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libfontconfig.so.1.12.0 libfontconfig.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libz.so.1 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libz.so.1.2.11 libz.so.1 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libfontconfig.so.1 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libfontconfig.so.1.12.0 libfontconfig.so.1 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libffi.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libffi.so.6.0.4 libffi.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf liborc-0.4.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf liborc-0.4.so.0.28.0 liborc-0.4.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libxml2.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libxml2.so.2.9.9 libxml2.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libcroco-0.6.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libcroco-0.6.so.3.0.1 libcroco-0.6.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libgmodule-2.0.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libgmodule-2.0.so.0.5600.4 libgmodule-2.0.so.0 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libxml2.so.2 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libxml2.so.2.9.9 libxml2.so.2 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libfreetype.so.6 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libfreetype.so.6.17.1 libfreetype.so.6 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf liblcms2.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf liblcms2.so.2.0.8 liblcms2.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libgthread-2.0.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libgthread-2.0.so.0.5600.4 libgthread-2.0.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libcroco-0.6.so.3 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libcroco-0.6.so.3.0.1 libcroco-0.6.so.3 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libjpeg.so.8 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libjpeg.so.8.2.2 libjpeg.so.8 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libcairo-gobject.so.2 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libcairo-gobject.so.2.11702.0 libcairo-gobject.so.2 )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; rm -rf libgio-2.0.so )
( cd /opt/Signal/resources/app.asar.unpacked/node_modules/sharp/vendor/lib ; ln -sf libgio-2.0.so.0.5600.4 libgio-2.0.so )

